### ISSUE TITLE
Attempting to retrieve playlists gives me access denied. 

### ISSUE THREAD

**Issue by gaussey** [Kaiede/PlexPlaylistHost#3]
Tried three different DNLA clients including my MusicCast receiver and none can access playlists under Music Channels/Playlists

Settings are as default of Localhost and port 32400

Sep 28, 2020 14:52:46.888 [2644] Debug — Plug-in com.plexapp.plugins.playlisthost has been used 15 times.
Sep 28, 2020 14:52:46.888 [2644] Debug — [com.plexapp.plugins.playlisthost] Sending command over HTTP (GET): /music/playlisthost
Sep 28, 2020 14:52:46.888 [2644] Debug — HTTP requesting GET http://127.0.0.1:7187/music/playlisthost
Sep 28, 2020 14:52:46.900 [4664] Debug — Request: [[::1]:13253 (Loopback)] GET /playlists (10 live) GZIP Signed-in
Sep 28, 2020 14:52:46.901 [4664] Debug — Completed: [[::1]:13253] 401 GET /playlists (10 live) GZIP 0ms 357 bytes
Sep 28, 2020 14:52:46.908 [2644] Debug — HTTP 500 response from GET http://127.0.0.1:7187/music/playlisthost
Sep 28, 2020 14:52:46.908 [2644] Debug — [com.plexapp.plugins.playlisthost] HTTP reply status 500, with 3018 bytes of content.
Sep 28, 2020 14:52:46.909 [4664] Debug — Completed: [127.0.0.1:13249] 500 GET /music/playlisthost (9 live) GZIP 21ms 1213 bytes
Sep 28, 2020 14:52:52.030 [3892] Debug — NetworkServiceBrowser: Parsing SSDP schema for http://192.168.0.17:49154/MediaRenderer/desc.xml
Sep 28, 2020 14:52:52.030 [3892] Debug — HTTP requesting GET http://192.168.0.17:49154/MediaRenderer/desc.xml
Sep 28, 2020 14:52:52.035 [3892] Debug — HTTP 200 response from GET http://192.168.0.17:49154/MediaRenderer/desc.xml

**Comment by Kaiede** [comment]
Looks like the request for playlists from Plex returned a 401 error, which means it was rejected.

I’m still not sure why some Plex installs work without a token, and some require them, but you’ll likely need the changes proposed in #2
