### ISSUE TITLE
Http 500 Response on music channels playlist won't work.

### ISSUE THREAD

**Issue by BuckTheWeasel** [Kaiede/PlexPlaylistHost#4]
hello, 

Thanks for development of this Plugin,
But i can't seem to get it to work at all sadly.

when i try to access the music channel and go intro playlist i get a loading screen 
but my serverlog say this : 
Request: [127.0.0.1:59949 (Loopback)] GET /music/playlisthost (8 live) GZIP Signed-in Token (username))
Plug-in com.plexapp.plugins.playlisthost has been used 9 times.
[com.plexapp.plugins.playlisthost] Sending command over HTTP (GET): /music/playlisthost
HTTP requesting GET http://127.0.0.1:59120/music/playlisthost
HTTP 500 response from GET http://127.0.0.1:59120/music/playlisthost
[com.plexapp.plugins.playlisthost] HTTP reply status 500, with 2993 bytes of content.
Completed: [127.0.0.1:59949] 500 GET /music/playlisthost (8 live) GZIP 1077ms 1238 bytes

I tried the following:
Chance the localhost to my local ip adres (did not work).
Chance the port (did not work).
Also tried to chance the code to use plex token (the plugin did not load at all when i try this,

Windows Server 2012.
Plex version: 1.21.1.3876 (puplic)

thanks for the help,
Buck,

**Comment by Kaiede** [comment]
So, there should be other logs from the plugin itself somewhere. What you have here is Plex's log, where the UPnP server is getting the 500 response code from the plugin. So the plugin is failing somewhere, but without the logs from the plugin itself, I can't really say why it isn't working.

**Comment by Kaiede** [comment]
Issue #3 for example, shows the URL request made to '/playlists' which is helpful.

**Comment by BuckTheWeasel** [comment]
hello,

thanks for the reply,

I see what you mean  
I found the log from the plugin itself i put it on pastebin:
https://pastebin.com/mktzDgeU

it seems this is the problem:
CRITICAL (core:574) - Exception (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PlaylistHost.bundle\Contents\Code\__init__.py", line 81, in MainMenu
    playlists = FetchPlaylists()
  File "C:\Users\Administrator\AppData\Local\Plex Media Server\Plug-ins\PlaylistHost.bundle\Contents\Code\__init__.py", line 171, in FetchPlaylists

this is also the unmodified version without the code to use plex token.

Thanks,
Buck,

**Comment by Kaiede** [comment]
Thanks for the log. Looking at the full exception, the error is at the very bottom:

> HTTPError: HTTP Error 401: Unauthorized

So this is the same issue as #3, and would be fixed with a proper implementation of #2. I’ll resolve this as a duplicate, but put a note in #2 that Windows servers likely need that work to unblock them.

Not sure why my QNAP didn’t require it.
